### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by sanhofman** [icapps/php-boilerplate#2]
Set-up full authentication:

**JWT authentication**
- Registration ✅ 
- Login ✅ 
- Refresh ✅ 
- Logout ✅ 
- Password reset ✅ 
- Password update ✅ 

**User** 
- Username/email/language/password ✅ 
- Active/blocked ✅ 
- Profile(s) ✅ 
- Activation/reset token(s) ✅ 

**User profile(s)**
- Get profile ✅ 
- Update profile ✅ 

**User devices**
- Multiple devices ✅ 
- Update device token ✅ 
- Remove device (logout) ✅

**Comment by domienjansen** [comment]
TODO: 
- Custom user provider voorzien (basis is er al IcappsUserProvider) ✅ 
- Translations voorzien voor standaard error messages ✅
